// ═══════════════════════════════════════
// ARTICLES AND CHAPTERS DATA
// To add an article: copy any {...} block inside ARTICLES and add to the array
// To add a chapter: copy any {n:..,t:..,s:..} block inside CHAPTERS
// ═══════════════════════════════════════

const ARTICLES = [
  {id:0,cat:'water',catL:'Water & Food',ch:'Ch. 2.2',title:'The Complete Water Security Protocol',expt:'Three-tier system: storage, filtration, and natural sourcing with precise calculations for your household.',time:'15 min',
  content:`<h4>Why Water Comes First</h4><p>The human body survives <strong>3–5 days without water</strong> — less than almost any other threat. In any serious crisis, your water situation determines your survival timeline more than any other single factor.</p><h4>Tier 1: Static Storage</h4><p>Minimum is <strong>2 litres per person per day</strong>. A family of four needs 24 litres for 72 hours, 112 litres for 2 weeks. Store in food-grade containers, out of direct sunlight. Rotate every 12 months.</p><h4>Tier 2: Filtration Capability</h4><p>Stored water runs out. The Sawyer Squeeze, Berkey gravity filter, or LifeStraw remove bacteria and protozoa without electricity. Supplement with iodine tablets. Learn the <strong>SODIS method</strong> (solar disinfection) as a zero-cost backup.</p><h4>Tier 3: Identified Sources</h4><p>Map 3 water sources within 5 km: rivers, lakes, wells, building tanks. Visit them in advance. Mark them on a paper map. Know which require treatment.</p><h4>Emergency Source: Your Own Building</h4><p>Most buildings hold 50–200 litres in the heating system and boiler. Learn to drain it using the lowest-point drain valve. This water requires boiling but is a critical reserve. Practice the technique before you need it.</p>`},
  {id:1,cat:'medical',catL:'Medical',ch:'Ch. 7.1',title:'Build a Tactical Civilian First Aid Kit',expt:'What belongs in a truly useful kit versus the decorative box most homes have.',time:'8 min',
  content:`<h4>The Problem with Standard Kits</h4><p>Off-the-shelf first aid kits are designed for minor office accidents. They are <strong>not designed for trauma</strong>. In a crisis, the injuries you'll encounter are different: lacerations, crush injuries, burns, and serious bleeding.</p><h4>The Minimum Trauma Kit</h4><p>Every civilian kit should contain: <strong>1 combat tourniquet (CAT or SOFTT-W)</strong>, an Israeli pressure bandage, haemostatic gauze (QuikClot or Celox), nitrile gloves, scissors/shears, and a CPR face shield. These address the leading causes of preventable death in trauma.</p><h4>Learn to Use It</h4><p>Book a <strong>Stop The Bleed course</strong> or equivalent. Practice tourniquet application on yourself with one hand. The procedure should take under 30 seconds.</p><h4>Medication Reserves</h4><p>Add: rehydration salts, activated charcoal, antiseptic, paracetamol, ibuprofen, antihistamine, and a <strong>3-month rolling supply</strong> of any critical prescriptions, rotated by expiry date.</p>`},
  {id:2,cat:'security',catL:'Security',ch:'Ch. 9.1',title:'The Grey Man Principle',expt:'How to move through crisis situations without drawing attention, suspicion, or becoming a target.',time:'6 min',
  content:`<h4>What Is Grey Man?</h4><p>"Grey Man" describes a strategy of appearing <strong>ordinary, unremarkable, and forgettable</strong> during a crisis. Move through an environment without triggering threat responses — from authorities, criminals, or desperate civilians.</p><h4>Appearance</h4><p>Avoid military-pattern clothing or tactical gear in public. These signal resources worth taking or a threat to be neutralised. Wear <strong>neutral, civilian clothing appropriate to your environment</strong>. Earth tones are fine; multicam is not.</p><h4>Behaviour</h4><p>Move with purpose but without urgency. Avoid eye contact that reads as challenge or fear. Don't draw attention by stopping, pointing, or showing strong emotional reactions. Move on the <strong>periphery</strong> of spaces, not the centre.</p><h4>What You Carry</h4><p>A civilian backpack in urban colours carries the same gear as a military pack without the signalling. Your go-bag should look like a school bag. Keep valuables concealed.</p>`},
  {id:3,cat:'energy',catL:'Energy',ch:'Ch. 2.4',title:'Off-Grid Power: A Priority List',expt:'The practical hierarchy of power backup from essential to advanced.',time:'7 min',
  content:`<h4>What You Actually Need Power For</h4><p>In a crisis, your power priorities are: <strong>lighting, device charging, and medical equipment</strong>. Everything else is comfort, not survival. Design your backup around these three functions first.</p><h4>Level 1: Headlamps</h4><p>Buy one <strong>quality headlamp per person</strong>. Modern rechargeable models (Petzl, Black Diamond) provide 6–200 hours of runtime and are the highest-value single preparedness purchase. Keep spare batteries.</p><h4>Level 2: Power Banks</h4><p>A 20,000–40,000 mAh bank charges a smartphone 5–10 times. Keep it at 80%. This handles comms for 7–10 days of moderate use.</p><h4>Level 3: Solar</h4><p>A 40–100W folding solar panel with a 500Wh portable power station (Jackery, EcoFlow) provides indefinite off-grid capability for phones, laptops, radios, and LED lighting — the highest-value resilience investment after water and food.</p>`},
  {id:4,cat:'evacuation',catL:'Evacuation',ch:'Ch. 3.5',title:'The 72-Hour Go-Bag: What Actually Goes In It',expt:'A weight-optimised, function-first packing list for rapid evacuation.',time:'10 min',
  content:`<h4>One Bag Per Person</h4><p>A go-bag only works if everyone can carry their own. <strong>Match weight to capacity</strong>: adults 10–15 kg, teenagers 6–8 kg, children 2–3 kg. An adult carrying the whole family's gear will be exhausted within 5 km.</p><h4>Core Categories</h4><p><strong>Water:</strong> 2L + LifeStraw. <strong>Food:</strong> 3 days calorie-dense, no-cook items. <strong>Documents:</strong> IDs, insurance, bank contacts (encrypted USB or laminated copies). <strong>Cash:</strong> Small bills for 3–7 days. <strong>Warmth:</strong> Emergency bivvy, extra socks, rain layer. <strong>Light:</strong> Headlamp + backup. <strong>Comms:</strong> Charged phone, power bank, paper contact list. <strong>First Aid:</strong> Compact trauma kit. <strong>Tools:</strong> Multitool, duct tape, fire-starters.</p><h4>Test It</h4><p>Pack the bag. Put it on. Walk 5 km. Adjust. A bag that works in theory but hasn't been worn is a liability.</p>`},
  {id:5,cat:'comms',catL:'Comms',ch:'Ch. 2.8',title:'Family Communication When the Network Is Down',expt:'Protocols that work when mobile networks, internet, and power are all unavailable.',time:'8 min',
  content:`<h4>The Network Will Fail</h4><p>Mobile networks become overloaded or physically destroyed within hours in serious crises. <strong>Never base your communication plan on mobile data or internet.</strong></p><h4>The Rally Point System</h4><p>Designate <strong>two pre-agreed rally points</strong>: one near home (specific park or corner), one further away (trusted contact 10+ km away). Every family member knows both and when to use each.</p><h4>Out-of-Area Contact</h4><p>Identify a contact who lives in another city and can relay messages between family members. Their number should be memorised by every adult and written on a card kept in wallets.</p><h4>Offline Comms</h4><p>Buy a <strong>battery/hand-crank AM/FM/shortwave radio</strong>. Emergency broadcasts, government communications, and amateur radio networks survive grid failure. A Kaito KA500 costs under €40 and is essential.</p>`},
  {id:6,cat:'psychology',catL:'Psychology',ch:'Ch. 8.7',title:'Stress Inoculation: Box Breathing',expt:'The most evidence-based technique for maintaining cognitive function under acute stress.',time:'5 min',
  content:`<h4>Why Stress Kills Decision-Making</h4><p>Under acute stress, blood flow to the prefrontal cortex — responsible for rational decisions — is reduced. Untrained people freeze, panic, or make catastrophic decisions. <strong>Stress inoculation is trainable.</strong></p><h4>Box Breathing (4-4-4-4)</h4><p>Used by Navy SEALs, first responders, and clinical psychologists. Inhale <strong>4 seconds</strong>. Hold <strong>4 seconds</strong>. Exhale <strong>4 seconds</strong>. Hold <strong>4 seconds</strong>. Repeat 4 cycles. This activates the parasympathetic nervous system, reducing heart rate and cortisol within 90 seconds.</p><h4>Build the Habit Before You Need It</h4><p>Practice daily for 2 weeks. The technique is only effective under stress if already automatic. Practice when calm, so it is available when you are not.</p>`},
  {id:7,cat:'water',catL:'Water & Food',ch:'Ch. 2.2',title:'Caloric Calculations: How Much Food Is Enough?',expt:'A simple framework for calculating your actual caloric needs across different crisis scenarios.',time:'6 min',
  content:`<h4>The Number That Matters</h4><p>Most people have no idea how many calories are in their "emergency food supply." A single adult needs approximately <strong>1500–2000 kcal per day at rest</strong>, and 2500–3500 kcal if performing physical labour or walking long distances.</p><h4>Calculate Your Reserve</h4><p>Multiply daily need × household size × days. A family of four, 2-week reserve at 2000 kcal/day = <strong>112,000 calories</strong>. Achievable with 15–20 kg of rice, lentils, oats, and canned goods.</p><h4>High-Density Foods</h4><p>Rice: 3,640 kcal/kg. Oats: 3,890 kcal/kg. Lentils: 3,500 kcal/kg. Peanut butter: 5,900 kcal/kg. Canned fish: 2,000–2,800 kcal/kg. A €150 investment in these staples provides a genuine 2-week reserve for a small family.</p>`},
  {id:8,cat:'security',catL:'Security',ch:'Ch. 14.2',title:'Checkpoint Behaviour: How to Pass Safely',expt:'The psychology and practice of interacting with armed checkpoints without escalating risk.',time:'5 min',
  content:`<h4>The Psychology</h4><p>People at checkpoints in crisis situations are often stressed and primed to see threats. Your job is to <strong>remove all ambiguity about your intentions</strong> and reduce their cognitive load.</p><h4>The Protocol</h4><p>Approach slowly. Hands visible. Window down before being asked. Documents ready. Speak calmly. <strong>Do not volunteer information beyond what is asked.</strong> Do not argue, assert rights, or demand explanations. The goal is to be completely unremarkable.</p><h4>What Not to Do</h4><p>Never reach suddenly into bags or glove compartments. Never make sudden movements. Never try to be charming in a way that could be misread. If you don't understand an instruction, ask calmly for clarification — never pretend you understood and do the wrong thing.</p>`},
];


const CHAPTERS = [
  {n:'0.1',t:'The Case for Preparedness',s:'Why competence is insurance'},
  {n:'1.1',t:'Signs of Systemic Collapse',s:'Recognising the 6 critical markers'},
  {n:'2.1',t:'Information Hygiene',s:'STOP protocol and threat monitoring'},
  {n:'2.2',t:'Water, Food & Sources',s:'Storage, filtration, and calculation'},
  {n:'2.3',t:'Physical & Medical Resources',s:'Fitness, medication reserves'},
  {n:'2.6',t:'Navigation & Maps',s:'GPS-free orientation methods'},
  {n:'2.7',t:'Financial Security',s:'Cash, documents, digital backup'},
  {n:'2.8',t:'Communication Protocols',s:'Family plans and rally points'},
  {n:'3.1',t:'Housing Risk Assessment',s:'Building types and vulnerabilities'},
  {n:'3.5',t:'Go-Bag Protocols',s:'72-hour emergency packs'},
  {n:'4.4',t:'Heat & Energy Independence',s:'Off-grid warmth and power'},
  {n:'5.1',t:'Urban Crisis Logistics',s:'Crowd behaviour and movement'},
  {n:'7.1',t:'First Aid & Trauma',s:'Tourniquet, wound care, CPR'},
  {n:'8.7',t:'Stress & Psychology',s:'Box breathing, decision-making under pressure'},
  {n:'9.1',t:'Grey Man Strategy',s:'Invisibility and security protocols'},
  {n:'12.1',t:'Chemical Threat Response',s:'Chlorine, toxic agents — correct response'},
  {n:'14.2',t:'Checkpoint Behaviour',s:'Interacting with authorities safely'},
  {n:'14.3',t:'Shelling Response',s:'What to do when under fire'},
];
